name: "build-and-unittest"

defaults:
  run:
    shell: "bash"

on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: "build-and-test"
    runs-on:
    - "windows-latest"
    defaults:
      run:
        shell: "bash"
    steps:
    - uses: "actions/checkout@v4"
    - 
      run: "dotnet restore src\\Cfd"
      name: "Restore project dependencies and tools"
    - 
      run: "dotnet build src\\Cfd"
      name: "Build project"
    - 
      run: |
        mkdir test-results
        dotnet test ./Cfd.Tests --logger:"junit;LogFilePath=test-results/dotnet-sample-cfd/xunit.xml"
      name: "Running tests"
    - 
      uses: "actions/upload-artifact@v4"
      with:
        name: "artifact_./Cfd.Tests/test-results"
        path: "./Cfd.Tests/test-results"
        retention-days: null
